/*
** EPITECH PROJECT, 2023
** Epitech-Raytracer
** File description:
** AFactory
*/

#ifndef EPITECH_RAYTRACER_AFACTORY_HPP
#define EPITECH_RAYTRACER_AFACTORY_HPP

#endif //EPITECH_RAYTRACER_AFACTORY_HPP
