##
## EPITECH PROJECT, 2022
## Epitech-Template
## File description:
## workflow.yml
##

# The goal of this workflow is to merge the remote branch into the Epitech remote, but only if the tests pass.

name: "Push to remote"
on: push

# Set your variables here
env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-OOP-400-LIL-4-1-raytracer-quentin.desmettre.git"
  EXECUTABLES: "raytracer"
  DEPENDENCIES: ""

jobs:
  test:
    name: Run tests before pushing to remote
    runs-on: "ubuntu-latest"

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
          fetch-depth: 0

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ env.DEPENDENCIES }}
          ./install_libconfig.sh
          sudo apt-get install -y libsfml-dev libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev libncurses-dev

      - name: Check if it compiles
        shell: bash
        run: |
          make
          make clean
          make fclean
          make re
          ls ${{ env.EXECUTABLES }}

      - name: Run tests (functional and unit)
        run: "make tests_run"

      - name: Push to Epitech
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
